<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-01-28T13:42:02 IST" name="Default suite" finished-at="2024-01-28T13:49:52 IST" duration-ms="470252">
    <groups>
    </groups>
    <test started-at="2024-01-28T13:42:02 IST" name="Default test" finished-at="2024-01-28T13:49:52 IST" duration-ms="470252">
      <class name="com.mystore.testcases.End2EndTest">
        <test-method is-config="true" signature="loadcofig()[pri:0, instance:com.mystore.testcases.End2EndTest@48aaecc3]" started-at="2024-01-28T13:42:02 IST" name="loadcofig" finished-at="2024-01-28T13:42:02 IST" duration-ms="15" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loadcofig -->
        <test-method is-config="true" signature="setup()[pri:0, instance:com.mystore.testcases.End2EndTest@48aaecc3]" started-at="2024-01-28T13:42:02 IST" name="setup" finished-at="2024-01-28T13:42:11 IST" duration-ms="8879" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="endtoendtest()[pri:0, instance:com.mystore.testcases.End2EndTest@48aaecc3]" started-at="2024-01-28T13:42:11 IST" name="endtoendtest" finished-at="2024-01-28T13:49:51 IST" duration-ms="460088" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Your order on My Store is complete.] but found [Your order on My Shop is complete.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Your order on My Store is complete.] but found [Your order on My Shop is complete.]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:575)
at org.testng.Assert.assertEquals(Assert.java:585)
at com.mystore.testcases.End2EndTest.endtoendtest(End2EndTest.java:73)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1510)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- endtoendtest -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:com.mystore.testcases.End2EndTest@48aaecc3]" started-at="2024-01-28T13:49:51 IST" name="teardown" finished-at="2024-01-28T13:49:52 IST" duration-ms="1197" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- com.mystore.testcases.End2EndTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
